proc template;
define style icon_dm;
   class fonts
      "Fonts used in the default style" /
      'TitleFont2' = ("<sans-serif>, Helvetica, sans-serif",4,bold italic)
      'TitleFont' = ("<sans-serif>, Helvetica, sans-serif",5,bold italic)
      'StrongFont' = ("<sans-serif>, Helvetica, sans-serif",4,bold)
      'EmphasisFont' = ("<sans-serif>, Helvetica, sans-serif",3,italic)
      'FixedEmphasisFont' = ("<monospace>, Courier, monospace",2,italic)
      'FixedStrongFont' = ("<monospace>, Courier, monospace",2,bold)
      'FixedHeadingFont' = ("<monospace>, Courier, monospace",2)
      'BatchFixedFont' = ("SAS Monospace, <monospace>, Courier, monospace",2)
      'FixedFont' = ("<monospace>, Courier",2)
      'headingEmphasisFont' = ("<sans-serif>, Helvetica, sans-serif",4,bold italic)
      'headingFont' = ("<sans-serif>, Helvetica, sans-serif",4,bold)
      'docFont' = ("<sans-serif>, Helvetica, sans-serif",3);
   class GraphFonts
      "Fonts used in graph styles" /
      'GraphDataFont' = ("<sans-serif>, <MTsans-serif>",7pt)
      'GraphUnicodeFont' = ("<MTsans-serif-unicode>",9pt)
      'GraphValueFont' = ("<sans-serif>, <MTsans-serif>",9pt)
      'GraphLabel2Font' = ("<sans-serif>, <MTsans-serif>",10pt)
      'GraphLabelFont' = ("<sans-serif>, <MTsans-serif>",10pt,bold)
      'GraphFootnoteFont' = ("<sans-serif>, <MTsans-serif>",10pt)
      'GraphTitleFont' = ("<sans-serif>, <MTsans-serif>",11pt,bold)
      'GraphTitle1Font' = ("<sans-serif>, <MTsans-serif>",14pt,bold)
      'GraphAnnoFont' = ("<sans-serif>, <MTsans-serif>",10pt);
   class color_list
      "Colors used in the default style" /
      'fgB2' = cx0066AA
      'fgB1' = cx004488
      'fgA4' = cxAAFFAA
      'bgA4' = cx880000
      'bgA3' = cxD3D3D3
      'fgA2' = cx0033AA
      'bgA2' = cxB0B0B0
      'fgA1' = cx000000
      'bgA1' = cxF0F0F0
      'fgA' = cx002288
      'bgA' = cxE0E0E0
      'bgX' = cx963634
        'fgX' = cx963634;
   class colors
      "Abstract colors used in the default style" /
      'headerfgemph' = color_list('fgA2')
      'headerbgemph' = color_list('bgA2')
      'headerfgstrong' = color_list('fgA2')
      'headerbgstrong' = color_list('bgA2')
      'headerfg' = color_list('fgA2')
      'headerbg' = color_list('bgA2')
      'datafgemph' = color_list('fgA1')
      'databgemph' = color_list('bgA3')
      'datafgstrong' = color_list('fgA1')
      'databgstrong' = color_list('bgA3')
      'datafg' = color_list('fgA1')
      'databg' = color_list('bgA3')
      'batchfg' = color_list('fgA1')
      'batchbg' = color_list('bgA3')
      'tableborder' = color_list('fgA1')
      'tablebg' = color_list('bgA1')
      'notefg' = color_list('fgA')
      'notebg' = color_list('bgA')
      'bylinefg' = color_list('fgA2')
      'bylinebg' = color_list('bgA2')
      'captionfg' = color_list('fgA1')
      'captionbg' = color_list('bgA')
      'proctitlefg' = color_list('fgA')
      'proctitlebg' = color_list('bgA')
      'titlefg' = color_list('fgA')
      'titlebg' = color_list('bgA')
      'systitlefg' = color_list('fgA')
      'systitlebg' = color_list('bgA')
      'Conentryfg' = color_list('fgA2')
      'Confolderfg' = color_list('fgA')
      'Contitlefg' = color_list('fgA')
      'link2' = color_list('fgB2')
      'link1' = color_list('fgB1')
      'contentfg' = color_list('fgA2')
      'contentbg' = color_list('bgA2')
      'docfg' = color_list('fgA')
      'docbg' = color_list('bgA')
        'testcolor' = color_list('bgX')
        'testbg' = color_list('bgX')
    'testfg' = color_list('fgX');
   class GraphColors
      "Abstract colors used in graph styles" /
      'gblockheader' = cxd8dae5
      'gcphasebox' = cx000000
      'gphasebox' = cxC2C9D8
      'gczonec' = cxB7C2DA
      'gzonec' = cxCBD3E3
      'gczoneb' = cxC0CBE4
      'gzoneb' = cxD2D9E9
      'gzonea' = cxDBE2F1
      'gcunder' = cx8EB778
      'gunder' = cx8EB778
      'gcover' = cxEFDF28
      'gover' = cxEFDF28
      'gcfinal' = cxC28262
      'gfinal' = cxC28262
      'gcinitial' = cxEFC328
      'ginitial' = cxEFC328
      'gcother' = cxEFDF28
      'gother' = cxEFDF28
      'gcmiss' = cx979797
      'gmiss' = cxD7D0CC
      'gablock' = cxF1F0F6
      'gblock' = cxD7DFEF
      'gcclipping' = cxDC531F
      'gclipping' = cxE7774F
      'gcstars' = cx000000
      'gstars' = cxB9CFE7
      'gcruntest' = cxBF4D4D
      'gruntest' = cxCAE3FF
      'gccontrollim' = cxBFC7D9
      'gcontrollim' = cxE6F2FF
      'gcerror' = cx000000
      'gerror' = cxB9CFE7
      'gcpredictlim' = cx003178
      'gpredictlim' = cxB9CFE7
      'gcpredict' = cx003178
      'gpredict' = cx003178
      'gcconfidence2' = cx780000
      'gcconfidence' = cx003178
      'gconfidence2' = cxE7B9B9
      'gconfidence' = cxB9CFE7
      'gcfit2' = cx780000
      'gcfit' = cx003178
      'gfit2' = cx780000
      'gfit' = cx003178
      'gcoutlier' = cx000000
      'goutlier' = cxB9CFE7
      'gcdata' = cx000000
      'gdata' = cxB9CFE7
      'greferencelines' = cx808080
      'gheader' = colors('testbg')
      'gconramp3cend' = cxFF0000
      'gconramp3cneutral' = cxFF00FF
      'gconramp3cstart' = cx0000FF
      'gramp3cend' = cxDD6060
      'gramp3cneutral' = cxFFFFFF
      'gramp3cstart' = cx6497EB
      'gconramp2cend' = cx6497EB
      'gconramp2cstart' = cxF3F7FE
      'gramp2cend' = cx5E528B
      'gramp2cstart' = cxEDEBF6
      'gtext' = cx000000
      'glabel' = cx000000
      'gborderlines' = cx000000
      'goutlines' = cx000000
      'gmgrid' = cxF4F4F4
      'ggrid' = cxECECEC
      'gaxis' = cx000000
      'gshadow' = cx000000
      'glegend' = cxFFFFFF
      'gfloor' = cxFFFFFF
      'gwalls' = cxFFFFFF
      'gckran5' = cx609530
      'gkran5' = cx7BB04A
      'gckran4' = cx9CB12D
      'gkran4' = cxB8CC49
      'gckran3' = cxD4BD2D
      'gkran3' = cxF2D94B
      'gckran2' = cxC2792D
      'gkran2' = cxE09346
      'gckran1' = cxB23D2E
      'gkran1' = cxD15845
      'gcdata12' = cxF9DA04
      'gcdata11' = cxB38EF3
      'gcdata10' = cx47A82A
      'gcdata9' = cxD17800
      'gcdata8' = cxB26084
      'gcdata6' = cx7F8E1F
      'gcdata7' = cx2597FA
      'gcdata4' = cx543005
      'gcdata5' = cx9D3CDB
      'gcdata3' = cx01665E
      'gcdata2' = cxB2182B
      'gcdata1' = cx2A25D9
      'gdata12' = cxDDD17E
      'gdata11' = cxB7AEF1
      'gdata10' = cx87C873
      'gdata9' = cxCF974B
      'gdata8' = cxCD7BA1
      'gdata6' = cxBABC5C
      'gdata7' = cx94BDE1
      'gdata4' = cxA9865B
      'gdata5' = cxB689CD
      'gdata3' = cx66A5A0
      'gdata2' = cxDE7E6F
      'gdata1' = cx7C95CA;
   class html
      "Common HTML text used in the default style" /
      'expandAll' = "<span onclick=""expandCollapse()"">"
      'posthtml flyover line' = "</span><hr size=""3""/>"
      'prehtml flyover line' = "<span><hr size=""3""/>"
      'prehtml flyover bullet' = %nrstr("<span><b>&#183;</b>")
      'posthtml flyover' = "</span>"
      'prehtml flyover' = "<span>"
      'break' = "<br/>"
      'Line' = "<hr size=""3""/>"
      'PageBreakLine' = "<p style=""page-break-after: always;""><br/></p><hr size=""3""/>"
      'fake bullet' = %nrstr("<b>&#183;</b>");
   class text
      "Common text." /
      'continued' = "(Continued)"
      'Fatal Banner' = "Fatal:"
      'Error Banner' = "Error:"
      'Warn Banner' = "Warning:"
      'Note Banner' = "Note:"
      'Pages Title' = "Table of Pages"
      'Content Title' = "Table of Contents"
      'suffix1' = " Procedure"
      'prefix1' = "The ";
   class Container /
      font = Fonts('DocFont')
      color = colors('testfg');
/*      backgroundcolor = colors('testcolor');*/
   class Index /
      color = colors('contentfg')
      backgroundcolor = colors('contentbg');
   class Document /
      doctype = "<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 3.2 Final//EN"">"
      contenttype = "text/html"
      protectspecialchars = auto
      linkcolor = colors('link2')
      activelinkcolor = colors('link1')
      visitedlinkcolor = colors('link1');
   class Body /
      marginright = 8
      marginleft = 8
      pagebreakhtml = html('PageBreakLine')
    ;
   class Frame /
      contentposition = left
      bodyscrollbar = auto
      bodysize = *
      contentscrollbar = auto
      contentsize = 23%
      framespacing = 1
      frameborderwidth = 4
      frameborder = on;
   class Contents /
      liststyletype = "decimal"
      tagattr = " onload=""expandAll()"""
      pagebreakhtml = html('break')
      color = colors('contentfg')
      
      marginright = 8
      marginleft = 8;
   class Pages /
      liststyletype = "decimal"
      tagattr = " onload=""expandAll()"""
      pagebreakhtml = html('break')
      color = colors('contentfg')
      backgroundcolor = colors('contentbg')
      marginright = 8
      marginleft = 8;
   class Date /
      width = 100%
      backgroundcolor = colors('contentbg')
      color = colors('contentfg');
   class BodyDate /
      verticalalign = top
      textalign = right
      borderspacing = 0
      cellpadding = 0
      backgroundcolor = colors('docbg')
      color = colors('docfg');
   class IndexItem /
      marginleft = 6pt
      posthtml = html('posthtml flyover')
      prehtml = html('prehtml flyover bullet')
      listentryanchor = on
      liststyletype = NONE
      backgroundcolor = _undef_
      color = colors('conentryfg');
   class ContentFolder /
      listentryanchor = off
      color = colors('confolderfg');
   class ByContentFolder /
      listentryanchor = on;
   class IndexProcName /
      listentryanchor = off
      liststyletype = "decimal"
      posthtml = html('posthtml flyover')
      prehtml = html('prehtml flyover')
      posttext = text('suffix1')
      pretext = text('prefix1')
      backgroundcolor = _undef_
      color = colors('contitlefg');
   class ContentProcLabel /
      posttext = _undef_
      pretext = _undef_;
   class PagesProcLabel /
      posttext = _undef_
      pretext = _undef_;
   class IndexTitle /
      posthtml = html('posthtml flyover line')
      prehtml = html('expandAll')
      font = fonts('EmphasisFont')
      backgroundcolor = _undef_
      color = colors('contitlefg');
   class ContentTitle /
      pretext = text('content title');
   class PagesTitle /
      pretext = text('pages title');
   class SysTitleAndFooterContainer /
      rules = NONE
      frame = VOID
      width = 100%
      cellpadding = 1
      borderspacing = 1
      borderwidth = 0;
   class TitleAndNoteContainer /
      rules = NONE
      frame = VOID
      width = 100%
      cellpadding = 1
      borderspacing = 1
      borderwidth = 0;
   class TitlesAndFooters /
      font = Fonts('TitleFont2')
      backgroundcolor = colors('systitlebg')
      color = colors('systitlefg');
   class BylineContainer /
      backgroundcolor = colors('Docbg')
      rules = NONE
      frame = VOID
      width = 100%
      cellpadding = 1
      borderspacing = 1
      borderwidth = 0;
   class SystemTitle /
      font = Fonts('TitleFont');
   class SystemFooter /
      font = Fonts('TitleFont');
   class PageNo /
      verticalalign = top
      textalign = right
      borderspacing = 0
      cellpadding = 0
      font = fonts('strongFont');
   class ExtendedPage /
      textalign = left
      cellpadding = 2pt
      borderstyle = solid
      borderwidth = 1pt
      fillrulewidth = 0.5pt
      posttext = ", which would not fit on a single physical page"
      pretext = "Continuing contents of page "
      frame = box
      font = fonts('EmphasisFont');
   class Byline /
      borderspacing = 0
      cellpadding = 0
      font = fonts('headingFont')
      backgroundcolor = colors('bylinebg')
      color = colors('bylinefg');
   class Parskip /
      backgroundcolor = _undef_
      color = _undef_
      borderwidth = 0
      rules = NONE
      frame = void
      borderspacing = 0
      cellpadding = 0
      font = fonts('headingFont');
   class Continued /
      width = 100%
      pretext = text('continued')
      borderspacing = 0
      cellpadding = 0
      font = fonts('headingFont');
   class ProcTitle /
      backgroundcolor = colors('proctitlebg')
      color = colors('proctitlefg');
   class ProcTitleFixed /
      font = fonts('FixedStrongFont');
   class Output /
      bordercollapse = separate
      backgroundcolor = colors('tablebg')
      rules = GROUPS
      frame = BOX
      cellpadding = 7
      borderspacing = 1
      bordercolor = colors('tableborder')
      borderstyle = solid
      borderwidth = 1;
   class Table;
   class Batch /
      font = fonts('BatchFixedFont')
      color = colors('batchfg')
      backgroundcolor = colors('batchbg')
      padding = 7;
   class Note /
      backgroundcolor = colors('notebg')
      color = colors('notefg');
   class NoteBanner /
      fontweight = bold
      pretext = text('Note Banner');
   class UserText;
   class PrePage /
      textalign = left;
   class NoteContentFixed /
      font = fonts('FixedFont');
   class WarnBanner /
      fontweight = bold
      pretext = text('Warn Banner');
   class WarnContentFixed /
      font = fonts('FixedFont');
   class ErrorBanner /
      fontweight = bold
      pretext = text('Error Banner');
   class ErrorContentFixed /
      font = fonts('FixedFont');
   class FatalBanner /
      fontweight = bold
      pretext = text('Fatal Banner');
   class FatalContentFixed /
      font = fonts('FixedFont');
   class Data /
      color = colors('testfg')
      textalign= left;
/*      backgroundcolor = colors('testbg');*/
   class DataFixed /
      font = fonts('FixedFont');
   class DataEmphasis /
      color = colors('datafgemph')
      backgroundcolor = colors('databgemph')
      font = fonts('EmphasisFont');
   class DataEmphasisFixed /
      font = fonts('FixedEmphasisFont');
   class DataStrong /
      color = colors('datafgstrong')
      backgroundcolor = colors('databgstrong')
      font = fonts('StrongFont');
   class LineContent /
      backgroundcolor = colors('notebg')
      color = colors('notefg');
   class DataStrongFixed /
      font = fonts('FixedStrongFont');
   class HeadersAndFooters /
      font = fonts('HeadingFont')
      color = colors('headerfg')
      backgroundcolor = colors('headerbg');
   class Caption /
      borderspacing = 0
      cellpadding = 0
      color = colors('captionfg')
      backgroundcolor = colors('captionbg');
   class AfterCaption /
      paddingtop = 4pt;
   class Header;
   class HeaderFixed /
      font = fonts('FixedFont');
   class HeaderEmphasis /
      color = colors('headerfgemph')
      backgroundcolor = colors('headerbgemph')
      font = fonts('EmphasisFont');
   class HeaderEmphasisFixed /
      font = fonts('FixedEmphasisFont');
   class HeaderStrong /
      color = colors('headerfgstrong')
      backgroundcolor = colors('headerbgstrong')
      font = fonts('StrongFont');
   class HeaderStrongFixed /
      font = fonts('FixedStrongFont');
   class RowHeader;
   class RowHeaderFixed /
      font = fonts('FixedFont');
   class RowHeaderEmphasis /
      font = fonts('EmphasisFont');
   class RowHeaderEmphasisFixed /
      font = fonts('FixedEmphasisFont');
   class RowHeaderStrong /
      font = fonts('StrongFont');
   class RowHeaderStrongFixed /
      font = fonts('FixedStrongFont');
   class Footer;
   class FooterFixed /
      font = fonts('FixedFont');
   class FooterEmphasis /
      font = fonts('EmphasisFont');
   class FooterEmphasisFixed /
      font = fonts('FixedEmphasisFont');
   class FooterStrong /
      font = fonts('StrongFont');
   class FooterStrongFixed /
      font = fonts('FixedStrongFont');
   class RowFooter;
   class RowFooterFixed /
      font = fonts('FixedFont');
   class RowFooterEmphasis /
      font = fonts('EmphasisFont');
   class RowFooterEmphasisFixed /
      font = fonts('FixedEmphasisFont');
   class RowFooterStrong /
      font = fonts('StrongFont');
   class RowFooterStrongFixed /
      font = fonts('FixedStrongFont');
   class ListItem /
      font = Fonts('DocFont');
   class Paragraph /
      font = Fonts('DocFont');
   class List /
      liststyletype = disc;
   class List2 /
      liststyletype = circle;
   class List3 /
      liststyletype = square;
   class Graph /
      cellpadding = 0
      backgroundcolor = colors('docbg');
   class GraphWalls /
      linethickness = 1px
      linestyle = 1
      frameborder = on
      contrastcolor = GraphColors('gaxis')
      backgroundcolor = GraphColors('gwalls')
      color = GraphColors('gwalls');
   class GraphAxisLines /
      tickdisplay = "outside"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gaxis')
      color = GraphColors('gaxis');
   class GraphGridLines /
      displayopts = "auto"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('ggrid')
      color = GraphColors('ggrid');
   class GraphMinorGridLines /
      displayopts = "auto"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gmgrid')
      color = GraphColors('gmgrid');
   class GraphOutlines /
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('goutlines')
      color = GraphColors('goutlines');
   class GraphBorderLines /
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gborderlines')
      color = GraphColors('gborderlines');
   class GraphReference /
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('greferencelines');
   class GraphTitle1Text /
      font = GraphFonts('GraphTitle1Font')
      color = GraphColors('gtext');
   class GraphTitleText /
      font = GraphFonts('GraphTitleFont')
      color = GraphColors('gtext');
   class GraphFootnoteText /
      font = GraphFonts('GraphFootnoteFont')
      color = GraphColors('gtext');
   class GraphDataText /
      font = GraphFonts('GraphDataFont')
      color = GraphColors('gtext');
   class GraphLabelText /
      font = GraphFonts('GraphLabelFont')
      color = GraphColors('glabel');
   class GraphLabel2Text /
      font = GraphFonts('GraphLabel2Font')
      color = GraphColors('glabel');
   class GraphValueText /
      font = GraphFonts('GraphValueFont')
      color = GraphColors('gtext');
   class GraphUnicodeText /
      font = GraphFonts('GraphUnicodeFont');
   class GraphBackground /
      backgroundcolor = colors('docbg')
      color = colors('docbg');
   class GraphFloor /
      backgroundcolor = GraphColors('gfloor')
      color = GraphColors('gfloor');
   class GraphLegendBackground /
      backgroundcolor = GraphColors('glegend')
      color = GraphColors('glegend');
   class GraphHeaderBackground /
      backgroundcolor = GraphColors('gheader')
      color = GraphColors('gheader');
   class DropShadowStyle /
      color = GraphColors('gshadow');
   class GraphDataDefault /
      endcolor = GraphColors('gramp3cend')
      neutralcolor = GraphColors('gramp3cneutral')
      startcolor = GraphColors('gramp3cstart')
      markersize = 7px
      markersymbol = "circle"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gcdata')
      color = GraphColors('gdata');
   class KPIRange1 /
      markersize = 7px
      markersymbol = "circle"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gckran1')
      color = GraphColors('gkran1');
   class KPIRange2 /
      markersize = 7px
      markersymbol = "circle"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gckran2')
      color = GraphColors('gkran2');
   class KPIRange3 /
      markersize = 7px
      markersymbol = "circle"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gckran3')
      color = GraphColors('gkran3');
   class KPIRange4 /
      markersize = 7px
      markersymbol = "circle"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gckran4')
      color = GraphColors('gkran4');
   class KPIRange5 /
      markersize = 7px
      markersymbol = "circle"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gckran5')
      color = GraphColors('gkran5');
   class GraphData1 /
      markersymbol = "circle"
      linestyle = 1
      contrastcolor = GraphColors('gcdata1')
      color = GraphColors('gdata1');
   class GraphData2 /
      markersymbol = "plus"
      linestyle = 4
      contrastcolor = GraphColors('gcdata2')
      color = GraphColors('gdata2');
   class GraphData3 /
      markersymbol = "X"
      linestyle = 8
      contrastcolor = GraphColors('gcdata3')
      color = GraphColors('gdata3');
   class GraphData4 /
      markersymbol = "triangle"
      linestyle = 5
      contrastcolor = GraphColors('gcdata4')
      color = GraphColors('gdata4');
   class GraphData5 /
      markersymbol = "square"
      linestyle = 14
      contrastcolor = GraphColors('gcdata5')
      color = GraphColors('gdata5');
   class GraphData6 /
      markersymbol = "asterisk"
      linestyle = 26
      contrastcolor = GraphColors('gcdata6')
      color = GraphColors('gdata6');
   class GraphData7 /
      markersymbol = "diamond"
      linestyle = 15
      contrastcolor = GraphColors('gcdata7')
      color = GraphColors('gdata7');
   class GraphData8 /
      linestyle = 20
      contrastcolor = GraphColors('gcdata8')
      color = GraphColors('gdata8');
   class GraphData9 /
      linestyle = 41
      contrastcolor = GraphColors('gcdata9')
      color = GraphColors('gdata9');
   class GraphData10 /
      linestyle = 42
      contrastcolor = GraphColors('gcdata10')
      color = GraphColors('gdata10');
   class GraphData11 /
      linestyle = 2
      contrastcolor = GraphColors('gcdata11')
      color = GraphColors('gdata11');
   class GraphData12 /
      contrastcolor = GraphColors('gcdata12')
      color = GraphColors('gdata12');
   class TwoColorRamp /
      endcolor = GraphColors('gramp2cend')
      startcolor = GraphColors('gramp2cstart');
   class TwoColorAltRamp /
      endcolor = GraphColors('gconramp2cend')
      startcolor = GraphColors('gconramp2cstart');
   class ThreeColorRamp /
      endcolor = GraphColors('gramp3cend')
      neutralcolor = GraphColors('gramp3cneutral')
      startcolor = GraphColors('gramp3cstart');
   class ThreeColorAltRamp /
      endcolor = GraphColors('gconramp3cend')
      neutralcolor = GraphColors('gconramp3cneutral')
      startcolor = GraphColors('gconramp3cstart');
   class GraphOutlier /
      linethickness = 2px
      linestyle = 42
      markersize = 7px
      markersymbol = "circle"
      contrastcolor = GraphColors('gcoutlier')
      color = GraphColors('goutlier');
   class GraphFit /
      linethickness = 2px
      linestyle = 1
      markersize = 7px
      markersymbol = "circle"
      contrastcolor = GraphColors('gcfit')
      color = GraphColors('gfit');
   class GraphFit2 /
      linethickness = 2px
      linestyle = 4
      markersize = 7px
      markersymbol = "X"
      contrastcolor = GraphColors('gcfit2')
      color = GraphColors('gfit2');
   class GraphConfidence /
      linethickness = 1px
      linestyle = 1
      markersize = 7px
      markersymbol = "triangle"
      contrastcolor = GraphColors('gcconfidence')
      color = GraphColors('gconfidence');
   class GraphConfidence2 /
      linethickness = 1px
      linestyle = 4
      markersize = 7px
      markersymbol = "diamond"
      contrastcolor = GraphColors('gcconfidence2')
      color = GraphColors('gconfidence2');
   class GraphPrediction /
      linethickness = 2px
      linestyle = 4
      markersize = 7px
      markersymbol = "plus"
      contrastcolor = GraphColors('gcpredict')
      color = GraphColors('gpredict');
   class GraphPredictionLimits /
      linethickness = 1px
      linestyle = 2
      markersize = 7px
      markersymbol = "chain"
      contrastcolor = GraphColors('gcpredictlim')
      color = GraphColors('gpredictlim');
   class GraphError /
      linethickness = 1px
      linestyle = 1
      markersize = 7px
      markersymbol = "asterisk"
      contrastcolor = GraphColors('gcerror')
      color = GraphColors('gerror');
   class GraphBar /
      displayopts = "fill outline";
   class GraphBox /
      capstyle = "serif"
      connect = "mean"
      displayopts = "fill caps median mean outliers";
   class GraphBoxMedian /
      linestyle = 1
      linethickness = 1px
      contrastcolor = GraphColors('gcdata');
   class GraphBoxMean /
      markersize = 9px
      markersymbol = "diamond"
      contrastcolor = GraphColors('gcdata');
   class GraphBoxWhisker /
      linestyle = 1
      linethickness = 1px
      contrastcolor = GraphColors('gcdata');
   class GraphHistogram /
      displayopts = "fill outline";
   class GraphEllipse /
      displayopts = "outline";
   class GraphBand /
      displayopts = "fill";
   class GraphContour /
      displayopts = "LabeledLineGradient";
   class GraphBlock /
      color = GraphColors('gblock');
   class GraphAltBlock /
      color = GraphColors('gablock');
   class GraphAnnoLine /
      linestyle = 1
      linethickness = 2px
      contrastcolor = GraphColors('gcdata');
   class GraphAnnoText /
      font = GraphFonts('GraphAnnoFont')
      color = GraphColors('gtext');
   class GraphAnnoShape /
      markersize = 12px
      markersymbol = "starfilled"
      linethickness = 2px
      linestyle = 1
      contrastcolor = GraphColors('gcdata')
      color = GraphColors('gdata');
   class GraphSelection /
      markersize = 11px
      markersymbol = "square"
      linethickness = 5px
      linestyle = 1
      contrastcolor = GraphColors('gcdata')
      color = GraphColors('gdata');
   class GraphConnectLine /
      linestyle = 1
      linethickness = 1px
      contrastcolor = GraphColors('gcdata');
   class GraphMissing /
      markersize = 7px
      markersymbol = "hash"
      linethickness = 1px
      linestyle = 2
      contrastcolor = GraphColors('gcmiss')
      color = GraphColors('gmiss');
   class GraphOther /
      contrastcolor = GraphColors('gcother')
      color = GraphColors('gother');
   class GraphInitial /
      contrastcolor = GraphColors('gcinitial')
      color = GraphColors('ginitial');
   class GraphFinal /
      contrastcolor = GraphColors('gcfinal')
      color = GraphColors('gfinal');
   class GraphOverflow /
      contrastcolor = GraphColors('gcover')
      color = GraphColors('gover');
   class GraphUnderflow /
      contrastcolor = GraphColors('gcunder')
      color = GraphColors('gunder');
   class GraphControlLimits /
      markersize = 7px
      markersymbol = "circle"
      linethickness = 1px
      linestyle = 1
      contrastcolor = GraphColors('gccontrollim')
      color = GraphColors('gcontrollim');
   class GraphRunTest /
      markersize = 7px
      markersymbol = "square"
      linethickness = 2px
      linestyle = 1
      contrastcolor = GraphColors('gcruntest')
      color = GraphColors('gruntest');
   class GraphStars /
      linethickness = 2px
      linestyle = 1
      contrastcolor = GraphColors('gcstars')
      color = GraphColors('gstars');
   class GraphClipping /
      markersize = 7px
      markersymbol = "circlefilled"
      linethickness = 2px
      linestyle = 2
      contrastcolor = GraphColors('gcclipping')
      color = GraphColors('gclipping');
   class GraphZoneA /
      color = GraphColors('gzonea');
   class GraphZoneB /
      contrastcolor = GraphColors('gczoneb')
      color = GraphColors('gzoneb');
   class GraphZoneC /
      contrastcolor = GraphColors('gczonec')
      color = GraphColors('gzonec');
   class GraphPhaseBox /
      contrastcolor = GraphColors('gcphasebox')
      color = GraphColors('gphasebox');
   class GraphBlockHeader /
      color = GraphColors('gblockheader');
   class LayoutContainer /
      cellpadding = 0
      borderspacing = 30
      borderwidth = 0
      frame = void
      rules = none
      backgroundcolor = _undef_;
end;
quit;
